# .pre-commit-config.yaml
# Pre-commit configuration for Python and web projects
# - Python: formatting, linting, security, modernization
# - General: whitespace, file endings, YAML, large files
# - Web: Prettier for JS/CSS/HTML/Markdown

repos:
  # -----------------------------
  # General code hygiene hooks
  # -----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements

  # -----------------------------
  # Python code quality & security
  # -----------------------------
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        language_version: python3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        entry: bandit -r . --skip B101
        pass_filenames: false

  # -----------------------------
  # Python docstring enforcement
  # -----------------------------
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        language_version: python3

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        language_version: python3
        additional_dependencies: ["setuptools"]

  # -----------------------------
  # Web & markup file formatting
  # -----------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        files: "\\.(md|markdown|yaml|yml)$"
# End of .pre-commit-config.yaml
