services:
  backend-app-debug:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app-debug
    env_file:
      - .env
    entrypoint: []
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --listen 0.0.0.0:${PYTHON_DEBUGGER_PORT} --wait-for-client \
        -m uvicorn backend.main:app --host 0.0.0.0 --port ${API_PORT}
    ports:
      - "${API_VSCODE_DEBUGGER_PORT}:${PYTHON_DEBUGGER_PORT}"
    depends_on:
      db:
        condition: service_healthy

  frontend-app-debug:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app-debug
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - PYTHONUNBUFFERED=1
    entrypoint: []
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python -Xfrozen_modules=off /tmp/debugpy --listen 0.0.0.0:${PYTHON_DEBUGGER_PORT} --wait-for-client \
        -m streamlit run frontend/streamlit_app.py --server.port=${STREAMLIT_PORT} --server.address=0.0.0.0
    ports:
      - "${STREAMLIT_VSCODE_DEBUGGER_PORT}:${PYTHON_DEBUGGER_PORT}"
    depends_on:
      - backend-app-debug
