services:
  backend-app:
    profiles:
      - debug-remote
    env_file:
      - .env
    entrypoint: []
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --listen 0.0.0.0:${API_VSCODE_DEBUGGER_PORT} --wait-for-client \
        -m uvicorn backend.main:app --host 0.0.0.0 --port ${API_PORT}
    ports:
      - "${API_DEBUG_PROFILE_PORT}:${API_PORT}"
      - "${API_VSCODE_DEBUGGER_PORT}:${API_VSCODE_DEBUGGER_PORT}"

  frontend-app:
    profiles:
      - debug-remote
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - PYTHONUNBUFFERED=1
    entrypoint: []
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python -Xfrozen_modules=off /tmp/debugpy --listen 0.0.0.0:${STREAMLIT_VSCODE_DEBUGGER_PORT} --wait-for-client \
        -m streamlit run frontend/streamlit_app.py --server.port=${STREAMLIT_PORT} --server.address=0.0.0.0
    ports:
      - "${STREAMLIT_DEBUG_PROFILE_PORT}:${STREAMLIT_PORT}"
      - "${STREAMLIT_VSCODE_DEBUGGER_PORT}:${STREAMLIT_VSCODE_DEBUGGER_PORT}"
