[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "0.1.0"
description = "Your backend package"
authors = [
    { name="Your Name", email="you@example.com" }
]
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "openai",
    "pydantic",
    "starlette",
    "requests",
    "debugpy",
    "pytest",
    "cryptography>=42.0.0",
    "pyopenssl>=24.0.0"
]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "pytest",
    "debugpy"
]
