[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "0.1.0"
description = "Your backend package"
authors = [
    { name="Your Name", email="you@example.com" }
]
dependencies = [
    # List your runtime dependencies here, e.g.:
    "fastapi",
    "sqlalchemy",
    "psycopg2-binary",
    # etc.
]
